var skillLevel  = [
  {skill : "HTML5", level : 7},
  {skill : "CSS3", level : 7},
  {skill : "JavaScript", level : 6},
  {skill : "jQuery", level : 6},
  {skill : "Ajax", level : 6},
  {skill : "Ruby", level : 8},
  {skill : "Ruby on Rails", level : 8},
  {skill : "Backbone.js", level : 5},
  {skill : "D3.js", level : 5},
  {skill : "SQL", level : 8},
  {skill : "MySQL", level : 8},
  {skill : "PostgreSQL", level : 8},
  {skill : "Bootstrap", level : 7},
  {skill : "Git", level : 7},
  {skill : "GitHub", level : 7},
  {skill : "Heroku", level : 7},
  {skill : "Amazon S3", level : 6},
  {skill : "Node.js", level : 3}
];
